services:

  frontend:
    user: "${DOCKER_USER:-1000}"
    build: 
      context: .
      dockerfile: ./src/frontend/Dockerfile
      target: frontend-production
      args:
        API_ORIGIN: "http://localhost:9801"
    image: hub:frontend-production
    ports:
      - "9800:3000"
